spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-classOname: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      dl-auto: create
    show-awl: true
    properties:
      hiberante:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  config: classpath:logback-spring-test.xml

